### ISSUE TITLE
`gh label create` does not work outside of git repository

### ISSUE THREAD

**Issue by razzius** [heaths/gh-label#13]
`gh label list` works using $GH_REPO, but `gh label create` exits with an error:

```
~ 23:55 $ echo $GH_REPO
razzius/dev-env-issues
~ 23:55 $ gh label list | head -3
bash    853A20
bug     d73a4a  Something isn't working
documentation   0075ca  Improvements or additions to documentation
~ 23:55 $ gh label create emacs
Error: failed to create label; error: gh returned error: exit status 1, stderr: unable to expand placeholder in path: fatal: not a git repository (or any of the parent directories): .git
/usr/local/bin/git: exit status 128
```

**Comment by heaths** [comment]
The GitHub CLI does not pass any context to extensions. Even the `-R owner/repo` global parameter I do support I had to add. I could add support, but I imagine most other extensions don't have it either. Instead, I recommend opening a linked issue on https://github.com/cli/cli to bolster support for extensions to avoid duplicate and likely incomplete context. /cc @vilmibm

**Comment by heaths** [comment]
For now I'd use the `-R org/repo` parameter, but I did file https://github.com/cli/go-gh/issues/5 to hopefully get some officially maintained support. For now I'd prefer not to try to reimplement every way the CLI itself supports specifying a repo.

**Comment by heaths** [comment]
I forgot I already parse `$GH_REPO` so I tried working on this and think it's a bug in the CLI. The `list` command was using the older placeholder syntax like `:owner` and `:repo` and worked, as you noted and I repro'd, but if I switch everything to `{owner}` and `{repo}` I get this same error about missing the _.git_ directory even on list.

@vilmibm does this sound like an issue in the CLI? This extension ultimately just calls the `gh` command similar to `go-gh` but supports `-R owner/repo` and `$GH_REPO` which, ultimately, both pass the owner and repo as parameters just as `gh api --help` show.

**Comment by ktowen** [comment]
For me it's not working even using `-R`

![image](https://user-images.githubusercontent.com/17689932/147291181-7d2768b3-79e3-4749-a0e2-939ac04c8c1c.png)
In the first attempt it creates it in the repo I'm inside, If I list the labels with `-R` it works correctly.

**Comment by heaths** [comment]
I tracked it down to a bug in the CLI. It's replacement tokens for REST vs GraphQL calls is inconsistent: they work in one case but not another. I'd have to parse the various config options to reproduce the desired behavior which, IMO, is not something extensions should have to do.
