### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by andypiper** [heaths/gh-label#19]
Running `gh upgrade --all` reports:

```
[graph]: already up to date
[label]: gh-label unsupported for darwin-arm64. Open an issue: `gh issue create -R heaths/gh-label -t'Support darwin-arm64'`
[markdown-preview]: upgrade complete
```

... so, raiding this issue!

**Comment by heaths** [comment]
Thanks for the suggestion! I [currently use](https://github.com/heaths/gh-label/blob/c88ca0348444bce74c56e7af601f4140f0cd1ba8/.github/workflows/release.yml#L31) https://github.com/cli/gh-extension-precompile to compile and publish the binaries, so you'll need to file a feature request there. The https://github.com/cli/cli will also likely need a change to check for and download darwin-arm64 releases as well.

/cc @vilmibm

**Comment by heaths** [comment]
There's a PR already available, but waiting for cli/cli changes: https://github.com/cli/gh-extension-precompile/pull/3

**Comment by mislav** [comment]
The [latest GitHub CLI 2.8.0 release](https://github.com/cli/cli/releases/tag/v2.8.0) fixes this by falling back to `amd64` binary if Rosetta is installed. If an `arm64` binary is found, for example as a product of the [latest gh-extension-precompile action](https://github.com/cli/gh-extension-precompile/releases/tag/v1.1.2), however, then its codesigning is fixed after downloading to allow execution by the OS.

**Comment by heaths** [comment]
@mislav so if I understand you correctly, if we can't/won't sign our arm64 binaries we should *not* upgrade to the latest gh-extension-precompile action?

**Comment by mislav** [comment]
@heaths We can not expect that every extension author signs their `arm64` binaries since that (to my knowledge) would require them to have a paid Apple Developer account. So, your binaries can remain unsigned; gh v2.8+ will self-sign any downloaded `arm64` extension during installation. You can safely upgrade to the latest `gh-extension-precompile`.
