### ISSUE TITLE
Error: failed to create label; error: gh returned error: exit status 1, stderr: gh: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by Nkr001** [heaths/gh-label#24]
Not working inside a container 
Using  command : gh label create feedback 
Error: failed to create label; error: gh returned error: exit status 1, stderr: gh: Not Found (HTTP 404)

**Comment by heaths** [comment]
Are you running this when the current working directory is a repo? Some commands don't currently work outside a repo.
