### ISSUE TITLE
Create command does not work

### ISSUE THREAD

**Issue by josemvidal** [heaths/gh-label#6]
The `gh label list` command works, but none of the others work. They do not appear to be installed:

```
> gh label create
Error: unknown command "create" for "label"
Run 'label --help' for usage.

> gh label --help
Usage:
  label [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  list        List labels for the repository matching optional 'label' substring in the name or description

Flags:
  -h, --help              help for label
  -R, --repo OWNER/REPO   Select another repository using the OWNER/REPO format

Use "label [command] --help" for more information about a command.
```

**Comment by heaths** [comment]
Thanks for the reminder. I haven't build and published the reminders for reasons in this [issue](https://github.com/cli/cli/issues/4194). In the meantime I just need to [do what @vilmibm did](https://github.com/cli/cli/issues/4194#issuecomment-914617600) so I don't unnecessarily bloat this repo and make `gh extension install` take forever.

If you have [Go](https://golang.org) installed, you can run `./build.sh` in the repo root wherever your extensions were downloaded e.g. in linux `~/.local/share/gh/extensions/gh-label/` and on Windows `%LocalAppData%\GitHub CLI\extensions\gh-label\`.

I'll try to get to this tonight.

**Comment by josemvidal** [comment]
Yes, it works now. Thanks!
